name: Auto Merge Releases

on:
  push:
    branches:
      - release/*
  workflow_dispatch: 

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set e-mail and username
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
      - name: Merge branches in sequence
        run: |
          MERGE_BRANCHES="${{ vars.MERGE_BRANCHES }}"
          MERGE_BRANCHES=$(echo $MERGE_BRANCHES | tr -d '\n' | tr -d ' ' | tr -d '"' | tr -d '[' | tr -d ']')
          IFS=','
          read -ra branches <<< "${MERGE_BRANCHES}"
          for (( i=0; i<${#branches[@]}-1; i++))
          do
            current="${branches[i]}"
            next="${branches[i+1]}"

            echo "Merging $current into $next"
            
            git fetch origin "$next"
            git checkout "$next"
            git merge "$current" || { echo "Merging failed, stopping..."; exit 1; }
            git push origin "$next"
          done