name: Auto Merge branches

on:
  push:
    branches:
      - release/*
  workflow_dispatch: 

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    outputs:
      confilct-files: ${{ steps.merge-branches.outputs.conflict-files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set e-mail and username
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Merge branches in sequence
        id: merge-branches
        run: |
          branches_string="${{ vars.MERGE_BRANCHES }}"
          IFS=',' read -ra branches <<< "$branches_string"  
          for ((i = 0; i < ${#branches[@]} - 1; i++)); do
            current="${branches[i]}"
            next="${branches[i+1]}"
            
            echo "------------ Merging $current into $next ------------"
            git fetch origin "$current"
            git fetch origin "$next"
            git checkout "$next"
            if ! git merge origin/"$current"; then
              echo "------------ Merging failed, $current into $next ------------"
              echo "------------ Conflict Files ------------"
              echo $(git ls-files -u | cut -f 2 | sort -u) >> $GITHUB_OUTPUT
              exit 1
            fi
            git push origin "$next"
          done

  merge-failed:
    runs-on: ubuntu-latest
    needs: merge-branches
    if: failure()
    steps:
      - name: echo failed message
        run: |
          echo "Merging failed, please resolve conflicts and try again"
          echo "Conflict files: ${{ needs.merge-branches.outputs.conflict-files }}"