name: Auto Merge Releases

on:
  push:
    branches:
      - release/*
  workflow_dispatch: 

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set e-mail and username
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
      - name: Merge branches in sequence
        run: |
          branches_string="${{ vars.MERGE_BRANCHES }}"
          branches_string=$(echo "$branches_string" | tr -d ' ') # remove unwanted spaces
          IFS=$'\n' branches=($branches_string)
          for ((i = 0; i < ${#branches[@]} - 1; i++)); do
            current="${branches[i]}"
            next="$(echo "${branches[i+1]}" | xargs)"  # remove trailing newline
            
            echo "Merging $current into $next"
            
            git fetch origin "$next"
            git checkout "$next"
            git merge "$current" || { echo "Merging failed, stopping..."; exit 1; }
            git push origin "$next"
          done