name: Auto Merge Releases

on:
  push:
    branches:
      - release/*
  workflow_dispatch: 
    
jobs:
  get-branch-list:
    runs-on: ubuntu-latest
    outputs:
      branch_list: ${{ steps.branch_list.outputs.branch_list }}
    steps:
      - name: Create branch list
        id: branch_list
        run: |
          list=$(echo "${{ vars.MERGE_BRANCHES }}" | tr '\n' ' ' | sed -e 's/release/\\"release/g' -e 's/$/\\"/' -e 's/ /\\", \\"/g')
          echo $list
          echo "branch_list=[ $list ]" >> $GITHUB_OUTPUT

  merge-release-branches:
    needs: get-branch-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.get-branch-list.outputs.branch_list) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set e-mail and username
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
        
      - name: Merge branch
        run: |
          git fetch origin release/${{ matrix.value }}
          git checkout release/${{ matrix.value }}
          git merge ${{ github.ref_name }}
          git push origin release/${{ matrix.value }}