name: auto-approve

on:
  pull_request:
    types: 
      - labeled

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.event.label.name == 'auto-approve'
    steps:
      - name: Review
        uses: hmarr/auto-approve-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}